# CONCLUSIONS

Seagrass decline is a globally recognised issue with far-reaching consequences. While the effects of this decline on coastal ecosystems have been extensively documented, a critical aspect has been systematically overlooked, the sediment microbial community. Given the gap in previous research, this doctoral thesis addresses these knowledge gaps by providing a comprehensive analysis of sediment microbial communities throughout the decline of a seagrass meadow. Moreover, it offers the first detailed description of sediment microbial communities underlying a *Cymodocea nodosa* seagrass meadow, for which only rhizosphere and epiphytic communities had previously been studied. In addition, it is among the first to use a combined metagenomic and metaproteomic approach to study microbial community metabolism, not only in seagrass sediments but also in coastal surface sediments, providing valuable data for further research. 

This thesis consists of three scientific articles that represent a stepwise progression of research: the first (**Dynamics of environmental conditions during the decline of a *Cymodocea nodosa* meadow**) documents the decline of the meadow alongside environmental conditions in the sediment; the second (**Compositional stability of sediment microbial communities during a seagrass meadow decline**) assesses the structure and dynamics of the sediment microbial communities; and the third (**Shift in the metabolic profile of sediment microbial communities during seagrass decline**) examines the metabolism of these microbial communities. The data presented in these scientific articles (Section 3) and discussed in Section 4 confirm the hypotheses: 

1. Decline of the *C. nodosa* meadow alters sediment environmental conditions; 

It is clear that the decline of the seagrass meadow changed the environmental conditions in the sediment. In particular, an increase in hydrogen sulphide concentration and the expansion of its accumulation zone was observed during the decline of the meadow.

2. The metabolic profile of the sediment microbial community differs with sediment depth, between the vegetated and nonvegetated sites, and throughout the study period;

The metabolic profile of the sediment microbial communities was primarily influenced by the decline of the seagrass meadow. Before the seagrass decline, differences in the metabolic profile of the microbial communities in the sediment were observed between the seagrass-vegetated and the nonvegetated site, especially differing in the deeper sediment parts and not differing closer to the sediment surface. During the decline, these differences in the deeper sediment diminished and the metabolic profile of the microbial communities in the sediment at the nonvegetated site began to resemble that of the vegetated site.

Interestingly, the microbial community composition did not follow the same trend, allowing only for a partial confirmation of the hypothesis:

3. The sediment microbial community structure differs with sediment depth, between the vegetated and nonvegetated sites, and throughout the study period;

Analysis of the V4 region of the 16S rRNA gene clearly showed that the microbial communities in the sediment were primarily stratified by sediment depth and secondarily differed between the seagrass-vegetated and nonvegetated site. In contrast to the metabolic profile of the communities, no temporal changes and thus no response to the decline of the seagrass could be observed in the structure of the microbial communities.

\bigskip
Taken together the collected data once again confirm the previously established notion that vegetated sediments harbour distinct microbial communities from the ones found in the nonvegetated sediments, but also highlight the great influence of the seagrass meadow
on the adjacent nonvegetated sediment, reflected in a highly similar microbial community in upper sediment parts. Throughout meadow decline the microbial communities underlying the seagrass meadow exhibit great stability, while the communities of the deeper layers of the adjacent sediment remain compositionally the same and adapt their metabolic profile as a response to greater availability of fresh organic matter. These communities become highly similar to those found in the seagrass sediment throughout the whole sediment core, indicating the intensified spread of seagrass derived organic matter throughout the whole area, in turn fuelling organic matter decomposition accompanied by high concentrations of hydrogen sulphide. In conclusion, the clear influence of seagrass on a wide sediment area has been demonstrated through assessment of environmental parameters and the use of molecular methods. This influence was only more emphasised with meadow decline, highlighting the broader ecological influence of the decline of seagrass meadows. The comprehensive temporal dataset generated, including data of sediment environmental conditions, microbial community composition, and metabolic functions, provides a strong foundation for further studies on sediment microbial communities of seagrass meadows and coastal surface sediment in general. 